pool:
  vmImage: 'Ubuntu-16.04'
  demands:
    - npm

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.1.505'
  inputs:
    version: 2.1.505
    
- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false
    
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'
  
- task: gulp@1
  displayName: 'Run gulp tasks'
